### ISSUE TITLE
Uncaught TypeError: Cannot read property 'define' of undefined

### ISSUE THREAD

**Issue by nyurik** [maputnik/editor#117]
Created a layer, and then tried to override it fully with the different JSON - the entire map went blank. Pasting:
```json
{
  "id": "building",
  "type": "fill-extrusion",
  "source": "kartotherian-meddo",
  "source-layer": "building",
  "paint": {
    "fill-extrusion-color": "#aaa",
    "fill-extrusion-opacity": 0.6,
    "fill-extrusion-height": 10,
    "fill-extrusion-base": 2
  },
  "layout": {
    "visibility": "visible"
  }
}
```

```js
s.prototype.applyPragmas = function(e, t) {
    var r = this;
    return e.replace(/#pragma mapbox: ([\w]+) ([\w]+) ([\w]+) ([\w]+)/g, function(e, n, a, i, o) {
        return r.pragmas[o]
>>>>          [n].concat(r.pragmas[o][t][n]).join("\n").replace(/{type}/g, i).replace(/{precision}/g, a)
    })
}
```

```js-stacktrace
141ac726b0f752a08e05.vendor.js:37 Uncaught TypeError: Cannot read property 'define' of undefined
    at http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:37:11268
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at s.applyPragmas (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:37:11170)
    at g.createProgram (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:27778)
    at g._createProgramCached (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:28625)
    at g.useProgram (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:28718)
    at s (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:5500)
    at i (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:4508)
    at a (http://88.99.164.208:6533/editor/141ac726b0f752a08e05.vendor.js:38:4413)
```

**Comment by orangemug** [comment]
Hey @nyurik I just tried to recreate this bug in the latest version using the openmaptiles source and got no error. Can you add some more details about the map source?

**Comment by orangemug** [comment]
Closing the issue. If someone experiences this issue again comment and we'll reopen.
