### ISSUE TITLE
Darwin release broken?

### ISSUE THREAD

**Issue by mcmayer** [maputnik/editor#56]
```bash
➜  ./maputnik_darwin --file style.json --watch
panic: unreachable

goroutine 1 [running]:
panic(0x328f00, 0xc420013590)
	/Users/travis/.gimme/versions/go1.7.4.darwin.amd64/src/runtime/panic.go:500 +0x1a1
main.assetFS(0x1)
	/Users/travis/gopath/src/github.com/maputnik/desktop/bindata_assetfs.go:221 +0x19d
main.main.func1(0xc420098640, 0xc420098640, 0xc42004fc17)
	/Users/travis/gopath/src/github.com/maputnik/desktop/maputnik.go:33 +0x42
github.com/urfave/cli.HandleAction(0x3356a0, 0x3d1300, 0xc420098640, 0xc420064420, 0x0)
	/Users/travis/gopath/src/github.com/urfave/cli/app.go:485 +0xd4
github.com/urfave/cli.(*App).Run(0xc420094ea0, 0xc42000c200, 0x4, 0x4, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x74f
main.main()
	/Users/travis/gopath/src/github.com/maputnik/desktop/maputnik.go:63 +0x245
```

I'm not quite sure what's going on, `maputnik_darwin --help` and `--version` do work, but nothing else does.

It'm using the newest Darwin release [v0.3.1](https://github.com/maputnik/editor/releases/download/v0.3.1/maputnik_darwin).

**Comment by lukasmartinelli** [comment]
Okay thanks for the report!
I'll add executing the CLI to the Travis tests to see wheter I can create a test regression.

**Comment by mcmayer** [comment]
Linux and Win are fine.

**Comment by lukasmartinelli** [comment]
Reuploaded fixed build to https://github.com/maputnik/editor/releases/tag/v0.3.1
Try it out again.

Thanks for reporting - now have a regression in travis for that.

**Comment by mcmayer** [comment]
perfect. Thanks!
